### ISSUE TITLE
Empty textbox error message is unhelpful for the user

### ISSUE THREAD

**Issue by tuansydau** [ahopk127/eecs2311-tab2xml#26] opened 2021-03-25 01:32 UTC
Product: Tab2XML
Operating System: Windows 10
Opened with: MuseScore (MuseScore)
Priority: minor

Description: When entering an empty text field, the error that shows up is unintuitive for the user and does not describe the issue at hand. 

Steps to Reproduce Error:

1. Open the project using Grade > Run.
2. Leaving the textbox empty, press the "Convert" at the bottom of the text area.

Expected Behaviour: The program should show an error message to the user that indicates that the text area is empty.

Actual Behaviour: The program shows an error message, but it is unintuitive for the user to understand.

Screenshots:
![image](https://user-images.githubusercontent.com/26176104/112405065-eeffaf00-8ce7-11eb-9ecc-aad2863cc958.png)

**Comment by ahopk127** [comment] 2021-03-25 12:26
Duplicate of #5.  Closed.

**Closed by ahopk127** 2021-03-25 12:26 UTC
Labels: duplicate
