### ISSUE TITLE
did not build due to Text Blocks being a preview feature 

### ISSUE THREAD

**Issue by Yalzahed** [ahopk127/eecs2311-tab2xml#29] opened 2021-03-25 03:52 UTC
ersion: March 17 2021 Master

Platform:
Windows 10
IntelliJ IDEA
Java 15.0.2

Reproduction:
When building the gradle project.

expected: the project should be able to build correctly when following the instructions in the user manual 

Actual: the following error was persistent when building the project 

error: text blocks are a preview feature and are disabled by default.
		String guitarPattern = "(^(?!((^(?!(([a-gA-G]#?)?[\\|-])[^\s]*?\\|).*$))).+\r?\n?){6,}";
		                                                                                         ^
Priority High- this prevents the user from opening the application.

Severity High- same reason as above

Potential fix: 
adding the following lines in the build.gradle seemed to fix the problem 
![image](https://user-images.githubusercontent.com/32556583/112416159-80c4e780-8cfb-11eb-9e29-747377eca2fa.png)
![image](https://user-images.githubusercontent.com/32556583/112416186-8fab9a00-8cfb-11eb-97fd-93fa62108a43.png)

**Comment by ahopk127** [comment] 2021-03-25 12:33
The string `"(^(?!((^(?!(([a-gA-G]#?)?[\|-])[^\s]?\|).$))).+\r?\n?){6,}"` is not a text block, I think the problem is actually the `\s` which should be `\\s` (and we should be able to replace `[^\s]` with `\\S`).  See [Text Blocks](https://docs.oracle.com/en/java/javase/15/text-blocks/index.html) and [Java's regex docs](https://docs.oracle.com/javase/tutorial/essential/regex/).

**Comment by ahopk127** [comment] 2021-03-25 18:26
Fixed on develop, will be in the next version.

**Closed as completed by ahopk127** 2021-03-25 18:26 UTC
Labels: bug, invalid
